version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: cd services/demo1 && pip install poetry && poetry install
      - sonarcloud/scan:
          project_root: 'services/demo1'

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud