version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.1.7
workflows:
  generate-config:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: services/demo1/.circleci/config.yml
          mapping: services/demo1/*