[tool.poetry]
name = "demo3"
version = "0.1.0"
description = ""
authors = ["criscapunal <crcaguilerapo@unal.edu.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
