version: 2.1

jobs:
  demo3-build:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: cd services/demo3 && pip install poetry && poetry install
      - sonarcloud/scan:
          project_root: services/demo3

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

workflows:
  demo3:
    jobs:
      - demo3-build:
          context: SonarCloud
