version: 2.1

jobs:
  demo3-build:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: cd services/demo3 && pip install poetry && poetry install

workflows:
  demo3:
    jobs:
      - demo3-build:
          context: SonarCloud
