version: 2.1

jobs:
  demo2-build:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: cd services/demo2 && pip install poetry && poetry install
      - sonarcloud/scan:
          project_root: services/demo2

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

workflows:
  demo2:
    jobs:
      - demo2-build:
          context: SonarCloud